# fly.toml app configuration file generated for challenge-db-prod on 2025-10-02T13:54:08+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'challenge-db-prod'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
