default: &default
  adapter: postgresql
  username: postgres
  password: password
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

  host: db
  port: 5432
  database: challenge_db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>