default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: password
  host: db
  port: 5432
  database: challenge_db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>


#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: postgres
#  password: password
#  host: db
#  port: 5432
#  url: <%= ENV['DATABASE_URL'] %>
#
#development:
#  <<: *default
#  database: challenge_db
#
#production:
#  <<: *default
#  database: challenge-db-dev


#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: postgres
#  password: password
#  host: db
#  port: 5432
#  url: <%= ENV['DATABASE_URL'] %>
#
#development:
#  <<: *default
#  database: challenge_db
#production:
#  url: <%= ENV['DATABASE_URL'] %>